### ISSUE TITLE
Little bug in flatpak version of Enve...

### ISSUE THREAD

**Issue by dadoprom** [MaurycyLiebner/enve#130] opened 2020-05-12 18:00 UTC
I installed Enve through flatpak and there is a little bug in the UI - there are 3 backslash characters where there are not suppose to be, see the screenshot...

![bug_enve_flatpak](https://user-images.githubusercontent.com/19377506/81728678-20cea500-948b-11ea-8c89-90cd20b70002.png)

**Comment by MaurycyLiebner** [comment] 2020-05-12 18:54
I've just run the flatpak and didn't encounter this issue, which is odd.

**Comment by dadoprom** [comment] 2020-05-12 19:45
> I've just run the flatpak and didn't encounter this issue, which is odd.

hmm, that is weird...

**Comment by eszlari** [comment] 2020-05-12 19:52
Could be related to: https://bugs.kde.org/show_bug.cgi?id=337491

@MaurycyLiebner I guess you are using GNOME. I can't reproduce this either (Plasma 5.18).

@dadoprom What's your distribution / Plasma version?

**Comment by dadoprom** [comment] 2020-05-12 20:20
![image](https://user-images.githubusercontent.com/19377506/81741384-c8a19e00-949e-11ea-8325-a44f472f5a82.png)

**Comment by eszlari** [comment] 2020-05-12 23:45
> I can't reproduce this either (Plasma 5.18).

I was wrong, I can reproduce this actually.

The bug seems to be in the Breeze theme. I changed the theme and the artifacts went away:

```
QT_STYLE_OVERRIDE=Fusion flatpak run io.github.maurycyliebner.enve
```

Flatpak allows us to set the environment variable by default, so we could use this as a workaround.

**Comment by dadoprom** [comment] 2020-05-12 23:56
Great, super!

**Comment by eszlari** [comment] 2020-05-13 07:26
I added the workaround to the manifest:

https://github.com/flathub/io.github.maurycyliebner.enve/commit/727925780b3d733d38ffbb80a0305841f933e244

**Comment by dadoprom** [comment] 2020-05-13 19:08
My Flatpak Enve got updated, this issue is no more. I think this can be closed.

**Comment by eszlari** [comment] 2020-05-15 09:18
>  I think this can be closed.

In case you don't know: you can close the issue yourself!

**Closed** 2020-05-15 11:39 UTC
