### ISSUE TITLE
Change Color fill makes Enve crash.

### ISSUE THREAD

**Issue by ebarranco** [MaurycyLiebner/enve#6] opened 2019-12-10 18:06 UTC
Changing Color fills on paths makes Enve crash. I show you the steps for reproduce the crash [in video here.](https://youtu.be/WDdM4uQ_IGM)

**Comment by MaurycyLiebner** [comment] 2019-12-10 18:35
I cannot reproduce the issue. Probably related to hardware (GPU) differences. I will look into it.

**Comment by MaurycyLiebner** [comment] 2019-12-10 18:41
Could you try keeping the fill color black, and then changing the shape of the path?

**Comment by ebarranco** [comment] 2019-12-10 19:02
Ok, I tried that and the software crash. [ I show you here.](https://youtu.be/O3efAqUArVc)

**Comment by MaurycyLiebner** [comment] 2019-12-10 19:23
Does changing the shape without the fill color result in a crash?

**Comment by ebarranco** [comment] 2019-12-10 19:27
No, it works just fine.

**Comment by MaurycyLiebner** [comment] 2019-12-10 20:06
https://www.dropbox.com/s/5yjyfyw59ghvix9/enve-0.0.0.i6.1aa.AppImage?dl=0
https://www.dropbox.com/s/x7i3rnuewrq11qa/enve-0.0.0.i6.2na.AppImage?dl=0
Does either of these crash when changing shapes, setting fill color?
They should draw red fill for all paths.

**Comment by ebarranco** [comment] 2019-12-10 20:38
Both, I show you [here](https://youtu.be/LfiYTSg-7yY).

**Comment by MaurycyLiebner** [comment] 2019-12-10 20:41
Does enve crash when you add an image and move it?

**Comment by ebarranco** [comment] 2019-12-10 20:52
No, I can scale, move, rotate and animate this parameters with an imported image without a crash.

**Comment by MaurycyLiebner** [comment] 2019-12-10 21:30
It is one of those 'it doesn't make sense' issues.
Just to be sure, please test with GPU rendering for path objects disabled:
https://www.dropbox.com/s/pri1d6qea42zuat/enve-0.0.0.i6.3cpu.AppImage?dl=0

**Comment by ebarranco** [comment] 2019-12-10 21:40
Everything works now! [Look here.](https://youtu.be/WqQIEI5o8cc)

**Comment by MaurycyLiebner** [comment] 2019-12-10 22:05
Sadly it doesn't really fix the problem. I simply disabled GPU rendering for paths, they are now rendered on your CPU. While that's not a deal-breaker, GPUs aren't superior to CPUs in path rendering (a single fx-6300 core is about equal to Radeon HD 5550), it is better to have the extra resources to use when rendering multiple frames and scenes with a lot of paths.

The parts of the code that can be responsible for the issue are quite extensive, and it is not feasible for me to fix it without owning a GPU that causes this problem.

Does anyone have an AMD/intel GPU and is impacted by #6?
Does anyone have an Nvidia GPU and is NOT impacted by #6?
If you are impacted by #6 please write your GPU model below.

**Comment by ebarranco** [comment] 2019-12-10 22:16
I understand. I'm impacted of course, my model is GeForce GTX 1050 Ti.

**Comment by bobpatraque** [comment] 2019-12-11 11:38
Mine is a Gtx 1080, with proprietary driver.

**Comment by eszlari** [comment] 2020-04-30 19:36
I can not reproduce this, it does not crash here!

OS: Kubuntu 20.04
GFX: Nvidia Geforce GTX 960
NVIDIA Driver Version: 440.64

@ebarranco What's output of `$ journalctl -f` when it crashes?

**Comment by eszlari** [comment] 2020-04-30 19:45
@MaurycyLiebner 

The option `Edit > Settings... > Path GPU acceleration` is not saved after closing the application, how can I be sure it was applied?

**Comment by MaurycyLiebner** [comment] 2020-05-01 11:14
I think the issue is present only with Nouveau driver. I guess it could have something to do with threaded OpenGL.

**Comment by MaurycyLiebner** [comment] 2020-05-01 11:23
> The option `Edit > Settings... > Path GPU acceleration` is not saved after closing the application, how can I be sure it was applied?

If you have an Nvidia GPU, path GPU acceleration settings are overridden on application startup.
If you enable path acceleration it is enabled until you close the app.

I made some changes to the way paths are rendered (simple paths do not get rasterized).
To test it, you have to add a raster effect (e.g., blur) to the path, to trigger rasterization.

**Comment by eszlari** [comment] 2020-05-01 15:12
>  To test it, you have to add a raster effect (e.g., blur) to the path, to trigger rasterization.

I tested that too: NO crash!

**Comment by MaurycyLiebner** [comment] 2020-05-01 15:38
@bobpatraque @ebarranco could you check whether this issue still occurs on your setup? Make sure to enable path GPU acceleration, and apply blur to the path.

**Comment by bobpatraque** [comment] 2020-05-01 19:48
For me, with proprietary driver, everything works ok, even without applying blur effect... I can change the color fill as many times as I want.

**Comment by MaurycyLiebner** [comment] 2020-05-04 09:51
How about with open-source drivers?

**Comment by bobpatraque** [comment] 2020-05-04 10:50
I had terrible issues with open source driver (it almost bricked my computer), I feel unconfortable testing it again...

**Comment by MaurycyLiebner** [comment] 2020-05-06 09:05
I will close this issue for now. Please reopen if you experience similar issues with Nvidia GPUs.

**Closed by MaurycyLiebner** 2020-05-06 09:05 UTC
Labels: bug, critical
