### ISSUE TITLE
pan viewport with a laptop

### ISSUE THREAD

**Issue by samytichadou** [MaurycyLiebner/enve#83] opened 2020-02-03 23:40 UTC
Right now, i'm not really able to pan viewport without using a real mouse on my laptop. I may have missed the "hand" tool, but i can't find a way to do it without having to zoom back, then zoom in pointing my cursor on the center of the viewport to manage to get viewport centered back for example.
Are there any shortcut for this ? or tool/command i missed ?

Cheers !

**Comment by MaurycyLiebner** [comment] 2020-02-04 11:03
You should be able to center the viewport with 0, from the numpad. It does not work right now because I set a single variable to true instead of false, it will be fixed with a next batch of commits.

**Comment by samytichadou** [comment] 2020-02-04 15:16
Nice i didn't know that ! But this remains problematic with laptop (my case) which does not have numpad. I still think it should be a way to pan the viewport without middle click mouse, but this can helps !

**Comment by dadoprom** [comment] 2020-02-04 15:44
I can confirm this issue... it is not possible to move the canvas with touchpad if there is no middle click mouse button... 

The way the moving canvas works in MOHO 12 is by using right mouse button for this.

- You hold the right button on mouse/touchpad - you move the canvas.
- You click the right button on mouse/touchpad - you have  the menu

It think this would be a good solution...

**Comment by MaurycyLiebner** [comment] 2020-02-06 12:53
I hope I didn't break anything.

**Closed** 2020-02-06 12:52 UTC
Labels: enhancement

**Comment by samytichadou** [comment] 2020-02-06 13:14
> 
> 
> I hope I didn't break anything.

i'll test it asap ! thanks for the fix !

**Comment by dadoprom** [comment] 2020-02-06 14:03
Just did a quick test, works as expected... works nicely with the touchpad... thanx!!
